### ISSUE TITLE
班级任务测试任务数据异常

### ISSUE THREAD

**Issue by ImYiFeng** [github123666/cidaren#11]
![Screenshot_2024-04-02-08-15-25-550_com tencent mm-edit](https://github.com/github123666/cidaren/assets/70053196/1a24295d-7d2a-4be7-bc9f-98f6cd7a1224)
![Screenshot_2024-04-02-08-15-59-490_com tencent mm](https://github.com/github123666/cidaren/assets/70053196/7c91553e-e16c-4e4a-bd1a-be2a758fe99b)
如图所示，词达人分数与用时挂钩
其实分数无所谓，但用时50秒还是太离谱了点，选择题限时不到10秒，补全也限时最多30秒，这个50s数据很明显是异常的

**Comment by github123666** [comment]
> ![Screenshot_2024-04-02-08-15-25-550_com tencent mm-edit](https://private-user-images.githubusercontent.com/70053196/318599441-1a24295d-7d2a-4be7-bc9f-98f6cd7a1224.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjM1NDMsIm5iZiI6MTcxMjAyMzI0MywicGF0aCI6Ii83MDA1MzE5Ni8zMTg1OTk0NDEtMWEyNDI5NWQtN2QyYS00YmU3LWJjOWYtOThmNmNkN2ExMjI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAyMDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNzA5YWU4OTc1MTJiYTliMmQyNTllNWJjNzhiMzg4YTA2OTMyZmNlMzFlZDM4YzI1ZDI5OTgwZGFkMjZiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smGc0IgpTIqCyeCY3ZET81wpHe7H9qFVC6WDdC0liAs) ![Screenshot_2024-04-02-08-15-59-490_com tencent mm](https://private-user-images.githubusercontent.com/70053196/318599503-7c91553e-e16c-4e4a-bd1a-be2a758fe99b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjM1NDMsIm5iZiI6MTcxMjAyMzI0MywicGF0aCI6Ii83MDA1MzE5Ni8zMTg1OTk1MDMtN2M5MTU1M2UtZTE2Yy00ZTRhLWJkMWEtYmUyYTc1OGZlOTliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAyMDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzQwODIwOTFiNjczZWE1ODg2Nzg2ZDdhMjk1MjBmODJmYzc0MzI1ZTA1NDQyNDk2YTUyOTMyNTAyZjVkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wlthr2OrMSRjhD-cFpSoAZtK7kZg2HkmzXYkSryYHYU) 如图所示，词达人分数与用时挂钩 其实分数无所谓，但用时50秒还是太离谱了点，选择题限时不到10秒，补全也限时最多30秒，这个50s数据很明显是异常的

不好意思,我看看

**Comment by github123666** [comment]
> > ![Screenshot_2024-04-02-08-15-25-550_com tencent mm-edit](https://private-user-images.githubusercontent.com/70053196/318599441-1a24295d-7d2a-4be7-bc9f-98f6cd7a1224.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjM1NDMsIm5iZiI6MTcxMjAyMzI0MywicGF0aCI6Ii83MDA1MzE5Ni8zMTg1OTk0NDEtMWEyNDI5NWQtN2QyYS00YmU3LWJjOWYtOThmNmNkN2ExMjI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAyMDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNzA5YWU4OTc1MTJiYTliMmQyNTllNWJjNzhiMzg4YTA2OTMyZmNlMzFlZDM4YzI1ZDI5OTgwZGFkMjZiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smGc0IgpTIqCyeCY3ZET81wpHe7H9qFVC6WDdC0liAs) ![Screenshot_2024-04-02-08-15-59-490_com tencent mm](https://private-user-images.githubusercontent.com/70053196/318599503-7c91553e-e16c-4e4a-bd1a-be2a758fe99b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjM1NDMsIm5iZiI6MTcxMjAyMzI0MywicGF0aCI6Ii83MDA1MzE5Ni8zMTg1OTk1MDMtN2M5MTU1M2UtZTE2Yy00ZTRhLWJkMWEtYmUyYTc1OGZlOTliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAyMDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzQwODIwOTFiNjczZWE1ODg2Nzg2ZDdhMjk1MjBmODJmYzc0MzI1ZTA1NDQyNDk2YTUyOTMyNTAyZjVkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wlthr2OrMSRjhD-cFpSoAZtK7kZg2HkmzXYkSryYHYU) 如图所示，词达人分数与用时挂钩 其实分数无所谓，但用时50秒还是太离谱了点，选择题限时不到10秒，补全也限时最多30秒，这个50s数据很明显是异常的
> 
> 不好意思,我看看

应该是后端更新了,之前是前端验证的

**Comment by github123666** [comment]
> ![Screenshot_2024-04-02-08-15-25-550_com tencent mm-edit](https://private-user-images.githubusercontent.com/70053196/318599441-1a24295d-7d2a-4be7-bc9f-98f6cd7a1224.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzk2ODAsIm5iZiI6MTcxMjAzOTM4MCwicGF0aCI6Ii83MDA1MzE5Ni8zMTg1OTk0NDEtMWEyNDI5NWQtN2QyYS00YmU3LWJjOWYtOThmNmNkN2ExMjI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA2Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZDVjOThiOTRmZTAwMGFjY2I0MWFmYjQzNTA2Y2RhNmY3YjY4MDZjZDBhNWFlMTNjZjNiNDhlN2I2MmM3ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KyFI7Zr4zjrEd_cFetPMV9KeJhW1WE_OxlIX4mHb1Z4) ![Screenshot_2024-04-02-08-15-59-490_com tencent mm](https://private-user-images.githubusercontent.com/70053196/318599503-7c91553e-e16c-4e4a-bd1a-be2a758fe99b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzk2ODAsIm5iZiI6MTcxMjAzOTM4MCwicGF0aCI6Ii83MDA1MzE5Ni8zMTg1OTk1MDMtN2M5MTU1M2UtZTE2Yy00ZTRhLWJkMWEtYmUyYTc1OGZlOTliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA2Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NTE4NGVlMjk2YTA1ZWQ2MDk1ZDQyZTEyYjM4MzdkYmViOTNmMjg2ZGU5MDFmZWRhZjc2MDY1ZmUwZjA0YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y6Up4OJIWzD_hBppUdhPR4EQqfwsDrr4dQ7a9Z1tcCk) 如图所示，词达人分数与用时挂钩 其实分数无所谓，但用时50秒还是太离谱了点，选择题限时不到10秒，补全也限时最多30秒，这个50s数据很明显是异常的
实在不好意思之前代码没测试,现在已解决。感谢issue!!!

**Comment by imyifeng** [comment]
经测试分数已正常，但单个单词用时仍然是50s
