### ISSUE TITLE
使用Code，运行后报错 TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by ImYiFeng** [github123666/cidaren#9]
内容如下：

```
PS E:\Apps\Cidaren> python main.py
[2024-03-26 08:32:35] main INFO: 开始登录
[2024-03-26 08:32:35] main INFO: 侵权请联系删除
[2024-03-26 08:32:35] main INFO: github123666 <- github.com
[2024-03-26 08:32:35] main INFO: 初始化公共组件
[2024-03-26 08:32:36] basic_api INFO: 获取该本书的所有单词
Traceback (most recent call last):
  File "E:\Apps\Cidaren\main.py", line 231, in <module>
    run()
  File "E:\Apps\Cidaren\main.py", line 174, in run
    raise 'test'
TypeError: exceptions must derive from BaseException
```

**Comment by github123666** [comment]
我的问题,打包出错了

**Comment by github123666** [comment]
> 内容如下：
> 
> ```
> PS E:\Apps\Cidaren> python main.py
> [2024-03-26 08:32:35] main INFO: 开始登录
> [2024-03-26 08:32:35] main INFO: 侵权请联系删除
> [2024-03-26 08:32:35] main INFO: github123666 <- github.com
> [2024-03-26 08:32:35] main INFO: 初始化公共组件
> [2024-03-26 08:32:36] basic_api INFO: 获取该本书的所有单词
> Traceback (most recent call last):
>   File "E:\Apps\Cidaren\main.py", line 231, in <module>
>     run()
>   File "E:\Apps\Cidaren\main.py", line 174, in run
>     raise 'test'
> TypeError: exceptions must derive from BaseException
> ```
把174行的代码注释掉

**Comment by github123666** [comment]
> > 内容如下：
> > ```
> > PS E:\Apps\Cidaren> python main.py
> > [2024-03-26 08:32:35] main INFO: 开始登录
> > [2024-03-26 08:32:35] main INFO: 侵权请联系删除
> > [2024-03-26 08:32:35] main INFO: github123666 <- github.com
> > [2024-03-26 08:32:35] main INFO: 初始化公共组件
> > [2024-03-26 08:32:36] basic_api INFO: 获取该本书的所有单词
> > Traceback (most recent call last):
> >   File "E:\Apps\Cidaren\main.py", line 231, in <module>
> >     run()
> >   File "E:\Apps\Cidaren\main.py", line 174, in run
> >     raise 'test'
> > TypeError: exceptions must derive from BaseException
> > ```
> 
> 把174行的代码注释掉
重新拉一下代码在试试看,不好意思脑子抽了

**Comment by ImYiFeng** [comment]
> > > 内容如下：
> > > ```
> > > PS E:\Apps\Cidaren> python main.py
> > > [2024-03-26 08:32:35] main INFO: 开始登录
> > > [2024-03-26 08:32:35] main INFO: 侵权请联系删除
> > > [2024-03-26 08:32:35] main INFO: github123666 <- github.com
> > > [2024-03-26 08:32:35] main INFO: 初始化公共组件
> > > [2024-03-26 08:32:36] basic_api INFO: 获取该本书的所有单词
> > > Traceback (most recent call last):
> > >   File "E:\Apps\Cidaren\main.py", line 231, in <module>
> > >     run()
> > >   File "E:\Apps\Cidaren\main.py", line 174, in run
> > >     raise 'test'
> > > TypeError: exceptions must derive from BaseException
> > > ```
> > 
> > 
> > 把174行的代码注释掉
> > 重新拉一下代码在试试看,不好意思脑子抽了

已经成功运行，感谢解答❤️
